default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5

test:
  <<: *default
  host:     localhost
  database: formulae-test

development:
  <<: *default
  host:     localhost
  database: formulae-development

staging:
  <<: *default
  host: <%= ENV['FORMULAE_DATABASE_HOST'] %>
  username: <%= ENV['FORMULAE_DATABASE_USERNAME'] %>
  password: <%= ENV['FORMULAE_DATABASE_PASSWORD'] %>
  database: formulae-staging

production:
  <<: *default
  host: <%= ENV['FORMULAE_DATABASE_HOST'] %>
  username: <%= ENV['FORMULAE_DATABASE_USERNAME'] %>
  password: <%= ENV['FORMULAE_DATABASE_PASSWORD'] %>
  database: formulae-production
